---

# DATAFRAME BASICS

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a DataFrame
df = pd.DataFrame({'id':[1,2],
                   'store_nbr':[1, 2],
                   'family':['POULTRY', 'PRODUCE']
                  })
df

   id  store_nbr   family
0   1          1  POULTRY
1   2          2  PRODUCE

In [3]:
retail_df = pd.read_csv('Data/retail_2016_2017.csv')
retail_df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [4]:
oil = pd.read_csv('Data/oil.csv')
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [5]:
oil.shape

(1218, 2)

In [6]:
oil.index

RangeIndex(start=0, stop=1218, step=1)

In [7]:
oil.columns

Index(['date', 'dcoilwtico'], dtype='object')

In [8]:
oil.columns = ['price_date', 'oil_price']
oil

      price_date  oil_price
0     2013-01-01        NaN
1     2013-01-02      93.14
2     2013-01-03      92.97
3     2013-01-04      93.12
4     2013-01-07      93.20
...          ...        ...
1213  2017-08-25      47.65
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26

[1218 rows x 2 columns]

In [9]:
oil.axes

[RangeIndex(start=0, stop=1218, step=1),
 Index(['price_date', 'oil_price'], dtype='object')]

In [10]:
oil.dtypes

price_date     object
oil_price     float64
dtype: object

---

# EXPLORING DATAFRAMES

---

In [11]:
oil.head()

   price_date  oil_price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20

In [12]:
oil.tail()

      price_date  oil_price
1213  2017-08-25      47.65
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26

In [13]:
oil.sample(5)

     price_date  oil_price
656  2015-07-08      51.61
410  2014-07-29     104.91
264  2014-01-06      93.12
133  2013-07-05     103.09
299  2014-02-24     103.17

In [14]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price_date  1218 non-null   object
 1   oil_price   1175 non-null   float64
dtypes: float64(1), object(1)
memory usage: 19.2+ KB

In [15]:
oil.describe()

         oil_price
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000

In [16]:
oil.describe(include='all')

        price_date    oil_price
count         1218  1175.000000
unique        1218          NaN
top     2013-01-01          NaN
freq             1          NaN
mean           NaN    67.714366
std            NaN    25.630476
min            NaN    26.190000
25%            NaN    46.405000
50%            NaN    53.190000
75%            NaN    95.660000
max            NaN   110.620000

In [17]:
oil.describe(percentiles=[0.2, 0.4, 0.6, 0.8, 0.9])

         oil_price
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
20%      45.452000
40%      49.716000
50%      53.190000
60%      77.154000
80%      97.368000
90%     103.070000
max     110.620000

---

# ASSIGNMENT: DATAFRAME BASICS

---

In [18]:
df = pd.read_csv('Data/transactions.csv')
df

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [20]:
# Number of rows and columns
df.shape

(83488, 3)

In [21]:
# Names of the columns
df.columns

Index(['date', 'store_nbr', 'transactions'], dtype='object')

In [22]:
# Data types of each column
df.dtypes

date            object
store_nbr        int64
transactions     int64
dtype: object