---

# ACCESSING DATAFRAME COLUMNS

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [3]:
df['family']

0                          AUTOMOTIVE
1                           BABY CARE
2                              BEAUTY
3                           BEVERAGES
4                               BOOKS
                      ...
1054939                       POULTRY
1054940                PREPARED FOODS
1054941                       PRODUCE
1054942    SCHOOL AND OFFICE SUPPLIES
1054943                       SEAFOOD
Name: family, Length: 1054944, dtype: object

In [4]:
df.family

0                          AUTOMOTIVE
1                           BABY CARE
2                              BEAUTY
3                           BEVERAGES
4                               BOOKS
                      ...
1054939                       POULTRY
1054940                PREPARED FOODS
1054941                       PRODUCE
1054942    SCHOOL AND OFFICE SUPPLIES
1054943                       SEAFOOD
Name: family, Length: 1054944, dtype: object

In [5]:
df.family.nunique()

33

In [6]:
df.sales.mean()

np.float64(457.72248700136424)

In [8]:
df.family.value_counts().iloc[:5]

family
AUTOMOTIVE    31968
BABY CARE     31968
BEAUTY        31968
BEVERAGES     31968
BOOKS         31968
Name: count, dtype: int64

In [10]:
df.sales.sum()

np.float64(482871591.3271672)

In [11]:
df[['family', 'store_nbr']]

                             family  store_nbr
0                        AUTOMOTIVE          1
1                         BABY CARE          1
2                            BEAUTY          1
3                         BEVERAGES          1
4                             BOOKS          1
...                             ...        ...
1054939                     POULTRY          9
1054940              PREPARED FOODS          9
1054941                     PRODUCE          9
1054942  SCHOOL AND OFFICE SUPPLIES          9
1054943                     SEAFOOD          9

[1054944 rows x 2 columns]

In [13]:
df[['family', 'store_nbr']].iloc[:5]

       family  store_nbr
0  AUTOMOTIVE          1
1   BABY CARE          1
2      BEAUTY          1
3   BEVERAGES          1
4       BOOKS          1

---

# LABORATORY

---

In [19]:
oil = pd.read_csv('Data/oil.csv')
oil.columns = ['date', 'price']
oil.head()

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [21]:
oil[['price', 'date']]

      price        date
0       NaN  2013-01-01
1     93.14  2013-01-02
2     92.97  2013-01-03
3     93.12  2013-01-04
4     93.20  2013-01-07
...     ...         ...
1213  47.65  2017-08-25
1214  46.40  2017-08-28
1215  46.46  2017-08-29
1216  45.96  2017-08-30
1217  47.26  2017-08-31

[1218 rows x 2 columns]