---

# IDENTIFYING & DROPPING DUPLICATES

---

In [1]:
import pandas as pd
import numpy as np

In [3]:
product_df = pd.DataFrame(data={'product':['Dairy', 'Dairy', 'Dairy', 'Vegetables', 'Fruits'],
                                'price':[2.56, 2.56, 4.55, 2.74, 5.44]})
product_df

      product  price
0       Dairy   2.56
1       Dairy   2.56
2       Dairy   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [4]:
product_df.nunique()

product    3
price      4
dtype: int64

In [5]:
# Checking Duplicates
product_df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [6]:
# Checking Duplicates on 'product' column
product_df.duplicated(subset='product')

0    False
1     True
2     True
3    False
4    False
dtype: bool

In [7]:
# Dropping the duplicated row
product_df.drop_duplicates()

      product  price
0       Dairy   2.56
2       Dairy   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [11]:
# Dropping duplicated data only from column 'product', keeping last duplicated row and reseting index
product_df.drop_duplicates(subset='product', # select only this column
                           keep='last', # keep the last duplicated row
                           ignore_index=True) # resets the index

      product  price
0       Dairy   4.55
1  Vegetables   2.74
2      Fruits   5.44

---

In [33]:
oil = pd.read_csv('Data/oil.csv')
oil.columns = ['date', 'price']
oil['euro_price'] = oil['price'] * 1.1

# now we'll create a duplicated row from the last row using concat
oil = pd.concat([oil, oil.iloc[[-1]]], ignore_index=True) # usa doble[[]]
oil.tail()

            date  price  euro_price
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986
1218  2017-08-31  47.26      51.986

In [34]:
# now we'll duplicate the last row using '.loc[]'
oil.loc[len(oil)] = oil.iloc[-1].values
oil.tail()

            date  price  euro_price
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986
1218  2017-08-31  47.26      51.986
1219  2017-08-31  47.26      51.986

In [35]:
oil.shape

(1220, 3)

In [36]:
oil.nunique(dropna=False)

date          1218
price          999
euro_price     999
dtype: int64

In [37]:
oil.duplicated().sum()

np.int64(2)

In [39]:
oil.drop_duplicates(keep='last', ignore_index=True, inplace=True)

In [40]:
oil

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

---

# MV LABORATORY

---

In [28]:
import pandas as pd
import numpy as np

oil = pd.DataFrame({
    "fecha":  ["2024-01-01", "2024-01-02", "2024-01-03"],
    "precio": [75.0, 76.5, 77.2],
    "volumen": [1000, 1100, 1050]
})

In [30]:
# Caso A: CON .values
oil_a = oil.copy()
oil_a.loc[len(oil_a)] = oil_a.iloc[-1].values
# Resultado: ['2024-01-03', 77.2, 1050] asignado POR POSICIÓN
oil_a

        fecha  precio  volumen
0  2024-01-01    75.0     1000
1  2024-01-02    76.5     1100
2  2024-01-03    77.2     1050
3  2024-01-03    77.2     1050

In [31]:
# Caso B: SIN .values
oil_b = oil.copy()
oil_b.loc[len(oil_b)] = oil_b.iloc[-1]
# Resultado: Series con index ['fecha', 'precio', 'volumen'] 
# asignada POR NOMBRE DE COLUMNA
oil_b

        fecha  precio  volumen
0  2024-01-01    75.0     1000
1  2024-01-02    76.5     1100
2  2024-01-03    77.2     1050
3  2024-01-03    77.2     1050

In [32]:
oil.iloc[-1]

fecha      2024-01-03
precio           77.2
volumen          1050
Name: 2, dtype: object