---

# MISSING DATA

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
product_df = pd.DataFrame({'product':[pd.NA, 'Dairy', 'Dairy', pd.NA, 'Fruits'],
                           'price':[2.56, pd.NA, 4.55, 2.74, pd.NA],
                           'product_id':[1, 2, 3, 4, 5]})
product_df

  product price  product_id
0    <NA>  2.56           1
1   Dairy  <NA>           2
2   Dairy  4.55           3
3    <NA>  2.74           4
4  Fruits  <NA>           5

In [3]:
# Counting total Missing Values
product_df.isna().sum()

product       2
price         2
product_id    0
dtype: int64

In [4]:
product_df.isnull().sum()

product       2
price         2
product_id    0
dtype: int64

In [6]:
# Other way to see if your DataFrame has Missing Values, is by using the Method ".info()"
product_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     3 non-null      object
 1   price       3 non-null      object
 2   product_id  5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

---

Like with `Series`, the `.dropna()` and `.fillna()` methods let you **handle missing data** in a DataFrame by either removing them or replacing them with other values

In [7]:
product_df

  product price  product_id
0    <NA>  2.56           1
1   Dairy  <NA>           2
2   Dairy  4.55           3
3    <NA>  2.74           4
4  Fruits  <NA>           5

In [12]:
# FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. 
# Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, 
# set `pd.set_option('future.no_silent_downcasting', True)`
pd.set_option('future.no_silent_downcasting', True)

# Replacing all missing values in one line
product_df.fillna(0)

  product price  product_id
0       0  2.56           1
1   Dairy     0           2
2   Dairy  4.55           3
3       0  2.74           4
4  Fruits     0           5

In [16]:
# Replacing Nan Values per column
product_df.fillna({'price': 0})

  product price  product_id
0    <NA>  2.56           1
1   Dairy     0           2
2   Dairy  4.55           3
3    <NA>  2.74           4
4  Fruits     0           5

---

# ASSIGNMENT: MISSING DATA

---

In [26]:
oil = pd.read_csv('Data/oil.csv')
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

---

In [27]:
# Checking if there are missing values
oil.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [29]:
oil_zero = oil.fillna(0)
print(f'The Mean of Oil Price filled with 0 is: {oil_zero['dcoilwtico'].mean()}')

The Mean of Oil Price filled with 0 is: 65.32379310344828

In [30]:
mean_val = oil['dcoilwtico'].mean()
oil_mean = oil.fillna(mean_val)
print(f'The Mean of Oil Price filled with the Mean value is: {oil_mean['dcoilwtico'].mean()}')

The Mean of Oil Price filled with the Mean value is: 67.71436595744682