---

# FILTERING DATAFRAMES

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [3]:
# Filtering Method No. 1
df[df.date == '2016-10-28'][['date', 'sales', 'family']]

              date     sales                      family
536382  2016-10-28     8.000                  AUTOMOTIVE
536383  2016-10-28     0.000                   BABY CARE
536384  2016-10-28     9.000                      BEAUTY
536385  2016-10-28  2576.000                   BEVERAGES
536386  2016-10-28     0.000                       BOOKS
...            ...       ...                         ...
538159  2016-10-28   391.292                     POULTRY
538160  2016-10-28    78.769              PREPARED FOODS
538161  2016-10-28   993.760                     PRODUCE
538162  2016-10-28     0.000  SCHOOL AND OFFICE SUPPLIES
538163  2016-10-28     3.000                     SEAFOOD

[1782 rows x 3 columns]

In [4]:
# Filtering Method No. 2
df[df['date'] == '2016-10-28'][['date', 'sales', 'family']]

              date     sales                      family
536382  2016-10-28     8.000                  AUTOMOTIVE
536383  2016-10-28     0.000                   BABY CARE
536384  2016-10-28     9.000                      BEAUTY
536385  2016-10-28  2576.000                   BEVERAGES
536386  2016-10-28     0.000                       BOOKS
...            ...       ...                         ...
538159  2016-10-28   391.292                     POULTRY
538160  2016-10-28    78.769              PREPARED FOODS
538161  2016-10-28   993.760                     PRODUCE
538162  2016-10-28     0.000  SCHOOL AND OFFICE SUPPLIES
538163  2016-10-28     3.000                     SEAFOOD

[1782 rows x 3 columns]

In [5]:
# Filtering Method No. 3
df.loc[df['date'] == '2016-10-28', ['date', 'sales', 'family']]

              date     sales                      family
536382  2016-10-28     8.000                  AUTOMOTIVE
536383  2016-10-28     0.000                   BABY CARE
536384  2016-10-28     9.000                      BEAUTY
536385  2016-10-28  2576.000                   BEVERAGES
536386  2016-10-28     0.000                       BOOKS
...            ...       ...                         ...
538159  2016-10-28   391.292                     POULTRY
538160  2016-10-28    78.769              PREPARED FOODS
538161  2016-10-28   993.760                     PRODUCE
538162  2016-10-28     0.000  SCHOOL AND OFFICE SUPPLIES
538163  2016-10-28     3.000                     SEAFOOD

[1782 rows x 3 columns]

In [6]:
# Filtering Method No. 4
df.loc[df.date == '2016-10-28', ['date', 'sales', 'family']]

              date     sales                      family
536382  2016-10-28     8.000                  AUTOMOTIVE
536383  2016-10-28     0.000                   BABY CARE
536384  2016-10-28     9.000                      BEAUTY
536385  2016-10-28  2576.000                   BEVERAGES
536386  2016-10-28     0.000                       BOOKS
...            ...       ...                         ...
538159  2016-10-28   391.292                     POULTRY
538160  2016-10-28    78.769              PREPARED FOODS
538161  2016-10-28   993.760                     PRODUCE
538162  2016-10-28     0.000  SCHOOL AND OFFICE SUPPLIES
538163  2016-10-28     3.000                     SEAFOOD

[1782 rows x 3 columns]

---

## Applying Multiple Filters

In [7]:
df[(df['family'].isin(['CLEANING', 'DAIRY'])) & (df['sales'] > 0)].head()

           id        date  store_nbr    family   sales  onpromotion
568   1946512  2016-01-01         25  CLEANING   734.0            0
569   1946513  2016-01-01         25     DAIRY  1033.0           11
1789  1947733  2016-01-02          1  CLEANING   526.0            3
1790  1947734  2016-01-02          1     DAIRY   627.0           15
1822  1947766  2016-01-02         10  CLEANING  1216.0            4

In [8]:
df[(df.family.isin(['CLEANING', 'DAIRY'])) & (df.sales > 0)].head()

           id        date  store_nbr    family   sales  onpromotion
568   1946512  2016-01-01         25  CLEANING   734.0            0
569   1946513  2016-01-01         25     DAIRY  1033.0           11
1789  1947733  2016-01-02          1  CLEANING   526.0            3
1790  1947734  2016-01-02          1     DAIRY   627.0           15
1822  1947766  2016-01-02         10  CLEANING  1216.0            4

In [9]:
df.loc[df.family.isin(['CLEANING', 'DAIRY']) & (df.sales > 0)].head()

           id        date  store_nbr    family   sales  onpromotion
568   1946512  2016-01-01         25  CLEANING   734.0            0
569   1946513  2016-01-01         25     DAIRY  1033.0           11
1789  1947733  2016-01-02          1  CLEANING   526.0            3
1790  1947734  2016-01-02          1     DAIRY   627.0           15
1822  1947766  2016-01-02         10  CLEANING  1216.0            4

In [10]:
mask = df.family.isin(['CLEANING', 'DAIRY']) & (df.sales > 0)
df.loc[mask].head()

           id        date  store_nbr    family   sales  onpromotion
568   1946512  2016-01-01         25  CLEANING   734.0            0
569   1946513  2016-01-01         25     DAIRY  1033.0           11
1789  1947733  2016-01-02          1  CLEANING   526.0            3
1790  1947734  2016-01-02          1     DAIRY   627.0           15
1822  1947766  2016-01-02         10  CLEANING  1216.0            4

---

In [11]:
oil = pd.read_csv('Data/oil.csv')
oil['benchmark'] = 100
oil.head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN        100
1  2013-01-02       93.14        100
2  2013-01-03       92.97        100
3  2013-01-04       93.12        100
4  2013-01-07       93.20        100

In [12]:
oil.loc[oil.dcoilwtico > oil.benchmark]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
407  2014-07-24      102.76        100
408  2014-07-25      105.23        100
409  2014-07-28      105.68        100
410  2014-07-29      104.91        100
411  2014-07-30      104.29        100

[182 rows x 3 columns]

In [13]:
# Filtering by year == 2013
oil[oil.date.str[:4] == '2013']

           date  dcoilwtico  benchmark
0    2013-01-01         NaN        100
1    2013-01-02       93.14        100
2    2013-01-03       92.97        100
3    2013-01-04       93.12        100
4    2013-01-07       93.20        100
..          ...         ...        ...
256  2013-12-25         NaN        100
257  2013-12-26       99.18        100
258  2013-12-27       99.94        100
259  2013-12-30       98.90        100
260  2013-12-31       98.17        100

[261 rows x 3 columns]

In [14]:
oil.loc[oil.date.str[:4] == '2013'].head()

         date  dcoilwtico  benchmark
0  2013-01-01         NaN        100
1  2013-01-02       93.14        100
2  2013-01-03       92.97        100
3  2013-01-04       93.12        100
4  2013-01-07       93.20        100

In [15]:
# A Big Filtering - unifying 2 pre-filtering code
mask = (oil.date.str[:4] == '2013') & (oil.dcoilwtico > oil.benchmark)
oil.loc[mask]

           date  dcoilwtico  benchmark
131  2013-07-03      101.92        100
133  2013-07-05      103.09        100
134  2013-07-08      103.03        100
135  2013-07-09      103.46        100
136  2013-07-10      106.41        100
..          ...         ...        ...
204  2013-10-14      102.46        100
205  2013-10-15      101.15        100
206  2013-10-16      102.34        100
207  2013-10-17      100.72        100
208  2013-10-18      100.87        100

[76 rows x 3 columns]

---

# PRO TIP: USE OF THE QUERY METHOD

---

In [16]:
df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [17]:
df.query('family in ["CLEANING", "DAIRY"] and sales > 0')

              id        date  store_nbr    family   sales  onpromotion
568      1946512  2016-01-01         25  CLEANING   734.0            0
569      1946513  2016-01-01         25     DAIRY  1033.0           11
1789     1947733  2016-01-02          1  CLEANING   526.0            3
1790     1947734  2016-01-02          1     DAIRY   627.0           15
1822     1947766  2016-01-02         10  CLEANING  1216.0            4
...          ...         ...        ...       ...     ...          ...
1054853  3000797  2017-08-15          7     DAIRY  1279.0           25
1054885  3000829  2017-08-15          8  CLEANING  1198.0           13
1054886  3000830  2017-08-15          8     DAIRY  1330.0           24
1054918  3000862  2017-08-15          9  CLEANING  1439.0           25
1054919  3000863  2017-08-15          9     DAIRY   835.0           19

[62415 rows x 6 columns]

---

We can reference variables using `@` symbol

In [18]:
avg_sales = df.loc[:, 'sales'].mean()
avg_sales

np.float64(457.72248700136424)

In [19]:
df.query("family in ['CLEANING', 'DAIRY'] and sales > @avg_sales").sort_values(by='sales')

             id        date  store_nbr    family    sales  onpromotion
25879   1971823  2016-01-15         35  CLEANING    458.0            2
632717  2578661  2016-12-21         12     DAIRY    458.0           95
403235  2349179  2016-08-14         23     DAIRY    458.0            4
175040  2120984  2016-04-08         20     DAIRY    458.0            0
332681  2278625  2016-07-05         43     DAIRY    458.0            6
...         ...         ...        ...       ...      ...          ...
982714  2928658  2017-07-06         32  CLEANING   7435.0           25
870448  2816392  2017-05-04         32  CLEANING   7448.0           23
900148  2846092  2017-05-21         16  CLEANING   8817.0           31
989776  2935720  2017-07-10         30  CLEANING  10392.0           23
855598  2801542  2017-04-26         16  CLEANING  11377.0           44

[51864 rows x 6 columns]

---

```python
# Replicating the mask example with .query()
mask = (oil.date.str[:4] == '2013') & (oil.dcoilwtico > oil.benchmark)
oil.loc[mask]

```

---

In [20]:
oil.query("date.str[:4] == 2013")

ValueError: "slice" is not a supported function

In [21]:
# Since it's not possible to slice a string. We'll need to 'date' data type into a "datetime" column
oil['date'] = pd.to_datetime(oil['date'])
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1175 non-null   float64
 2   benchmark   1218 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 28.7 KB

In [26]:
oil.query("date.dt.year == 2013 or dcoilwtico > benchmark").sort_values(by='date')

          date  dcoilwtico  benchmark
0   2013-01-01         NaN        100
1   2013-01-02       93.14        100
2   2013-01-03       92.97        100
3   2013-01-04       93.12        100
4   2013-01-07       93.20        100
..         ...         ...        ...
407 2014-07-24      102.76        100
408 2014-07-25      105.23        100
409 2014-07-28      105.68        100
410 2014-07-29      104.91        100
411 2014-07-30      104.29        100

[367 rows x 3 columns]

---

# ASSIGNMENT: FILTERING DATAFRAMES

---

In [30]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [33]:
# Calculate the percentage of times all stores had more than 2000 transactions
(transactions.transactions > 2000).mean()

np.float64(0.26680481027213493)

In [52]:
# Calculate the percentage of times store 25 had more than 2000 transactions, AND 
# calculate the sum of transactions on these days
num = (transactions.query("store_nbr == 25 and transactions > 2000")['transactions'].count())
den = (transactions.query("store_nbr == 25")['transactions'].count())

result = num / den
result

np.float64(0.0346749226006192)

In [54]:
# total number of transactions more than 2000 for store 25
transactions.query("store_nbr == 25 and transactions > 2000")['transactions'].sum()

np.int64(144903)

In [42]:
# Sum the transactions for stores 25 and 31, that occurred in May or June, and had less than 2000 transactions
transactions.date = pd.to_datetime(transactions.date)
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [47]:
transactions.query("store_nbr in [25, 31] and (date.dt.month == 5 or date.dt.month == 6) and transactions < 2000")['transactions'].sum()

np.int64(644910)