---

# SORTING DATAFRAMES BY INDICES

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
retail_df = pd.read_csv('Data/retail_2016_2017.csv')
retail_df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [3]:
condition = retail_df.family.isin(['BEVERAGES', 'DELI', 'DAIRY'])

sample_df = retail_df[condition].sample(5, random_state=2021)
sample_df

             id        date  store_nbr     family     sales  onpromotion
74292   2020236  2016-02-11         43       DELI   212.000            2
13506   1959450  2016-01-08         38       DELI   131.545           43
882588  2828532  2017-05-11         23  BEVERAGES  1194.000           22
445008  2390952  2016-09-06         45  BEVERAGES  8339.000           19
495966  2441910  2016-10-05         25       DELI     0.000            0

---

## Sorting Indexm

In [4]:
# sorting by index downwards
sample_df.sort_index(ascending=False)

             id        date  store_nbr     family     sales  onpromotion
882588  2828532  2017-05-11         23  BEVERAGES  1194.000           22
495966  2441910  2016-10-05         25       DELI     0.000            0
445008  2390952  2016-09-06         45  BEVERAGES  8339.000           19
74292   2020236  2016-02-11         43       DELI   212.000            2
13506   1959450  2016-01-08         38       DELI   131.545           43

In [5]:
# sorting by column index upwards
sample_df.sort_index(axis=1)

              date     family       id  onpromotion     sales  store_nbr
74292   2016-02-11       DELI  2020236            2   212.000         43
13506   2016-01-08       DELI  1959450           43   131.545         38
882588  2017-05-11  BEVERAGES  2828532           22  1194.000         23
445008  2016-09-06  BEVERAGES  2390952           19  8339.000         45
495966  2016-10-05       DELI  2441910            0     0.000         25

---

# Sorting Values

In [8]:
# Sorting one Column
sample_df.sort_values(by='store_nbr')

             id        date  store_nbr     family     sales  onpromotion
882588  2828532  2017-05-11         23  BEVERAGES  1194.000           22
495966  2441910  2016-10-05         25       DELI     0.000            0
13506   1959450  2016-01-08         38       DELI   131.545           43
74292   2020236  2016-02-11         43       DELI   212.000            2
445008  2390952  2016-09-06         45  BEVERAGES  8339.000           19

In [9]:
# Sorting more than one column
sample_df.sort_values(by=['family', 'sales'], ascending=[True, False])

             id        date  store_nbr     family     sales  onpromotion
445008  2390952  2016-09-06         45  BEVERAGES  8339.000           19
882588  2828532  2017-05-11         23  BEVERAGES  1194.000           22
74292   2020236  2016-02-11         43       DELI   212.000            2
13506   1959450  2016-01-08         38       DELI   131.545           43
495966  2441910  2016-10-05         25       DELI     0.000            0

---

# LABORATORY

---

In [13]:
oil = pd.read_csv('Data/oil.csv')
oil['benchmark'] = 100
oil

            date  dcoilwtico  benchmark
0     2013-01-01         NaN        100
1     2013-01-02       93.14        100
2     2013-01-03       92.97        100
3     2013-01-04       93.12        100
4     2013-01-07       93.20        100
...          ...         ...        ...
1213  2017-08-25       47.65        100
1214  2017-08-28       46.40        100
1215  2017-08-29       46.46        100
1216  2017-08-30       45.96        100
1217  2017-08-31       47.26        100

[1218 rows x 3 columns]

In [14]:
# Sorting index
oil.sort_index(ascending=False)

            date  dcoilwtico  benchmark
1217  2017-08-31       47.26        100
1216  2017-08-30       45.96        100
1215  2017-08-29       46.46        100
1214  2017-08-28       46.40        100
1213  2017-08-25       47.65        100
...          ...         ...        ...
4     2013-01-07       93.20        100
3     2013-01-04       93.12        100
2     2013-01-03       92.97        100
1     2013-01-02       93.14        100
0     2013-01-01         NaN        100

[1218 rows x 3 columns]

In [15]:
# Sorting the columns
oil.sort_index(axis=1, ascending=False)

      dcoilwtico        date  benchmark
0            NaN  2013-01-01        100
1          93.14  2013-01-02        100
2          92.97  2013-01-03        100
3          93.12  2013-01-04        100
4          93.20  2013-01-07        100
...          ...         ...        ...
1213       47.65  2017-08-25        100
1214       46.40  2017-08-28        100
1215       46.46  2017-08-29        100
1216       45.96  2017-08-30        100
1217       47.26  2017-08-31        100

[1218 rows x 3 columns]

---

In [18]:
oil['month'] = oil['date'].astype('datetime64[ns]').dt.month
oil

            date  dcoilwtico  benchmark  month
0     2013-01-01         NaN        100      1
1     2013-01-02       93.14        100      1
2     2013-01-03       92.97        100      1
3     2013-01-04       93.12        100      1
4     2013-01-07       93.20        100      1
...          ...         ...        ...    ...
1213  2017-08-25       47.65        100      8
1214  2017-08-28       46.40        100      8
1215  2017-08-29       46.46        100      8
1216  2017-08-30       45.96        100      8
1217  2017-08-31       47.26        100      8

[1218 rows x 4 columns]

In [20]:
oil.sort_values(by=['dcoilwtico'], ascending=False)

            date  dcoilwtico  benchmark  month
178   2013-09-06      110.62        100      9
171   2013-08-28      110.17        100      8
179   2013-09-09      109.62        100      9
170   2013-08-27      109.11        100      8
182   2013-09-12      108.72        100      9
...          ...         ...        ...    ...
1079  2017-02-20         NaN        100      2
1118  2017-04-14         NaN        100      4
1149  2017-05-29         NaN        100      5
1174  2017-07-03         NaN        100      7
1175  2017-07-04         NaN        100      7

[1218 rows x 4 columns]

In [21]:
oil.sort_values(by=['month', 'dcoilwtico'], ascending=[True, False])

            date  dcoilwtico  benchmark  month
282   2014-01-30       98.25        100      1
21    2013-01-30       97.98        100      1
22    2013-01-31       97.65        100      1
20    2013-01-29       97.62        100      1
283   2014-01-31       97.55        100      1
...          ...         ...        ...    ...
774   2015-12-21       34.55        100     12
256   2013-12-25         NaN        100     12
517   2014-12-25         NaN        100     12
778   2015-12-25         NaN        100     12
1039  2016-12-26         NaN        100     12

[1218 rows x 4 columns]

---

# ASSIGNMENT: 

---

In [23]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [26]:
# Q1. 5 days with the highest transactions counts, any similarities between them?
transactions.sort_values(by='transactions', ascending=False).head()

             date  store_nbr  transactions
52011  2015-12-23         44          8359
71010  2016-12-23         44          8307
16570  2013-12-23         44          8256
33700  2014-12-23         44          8120
16572  2013-12-23         46          8001

In [32]:
# Q2. Dataset sorted by date from earliest to most recent, but with the highest transactions first
transactions.sort_values(by=['date', 'transactions'], ascending=[True, False]).head()

          date  store_nbr  transactions
0   2013-01-01         25           770
40  2013-01-02         46          4886
38  2013-01-02         44          4821
39  2013-01-02         45          4208
41  2013-01-02         47          4161

In [33]:
# Q3. Sort the columns in reverse alphabetical order.
transactions.sort_index(axis=1, ascending=False).head()

   transactions  store_nbr        date
0           770         25  2013-01-01
1          2111          1  2013-01-02
2          2358          2  2013-01-02
3          3487          3  2013-01-02
4          1922          4  2013-01-02