---

# ARITHMETIC COLUMN CREATION

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [4]:
df_tax = df.copy()
df_tax['tax_amount'] = round(df_tax['sales']*0.05, 3)
df_tax['total'] = df_tax['sales'] + df_tax['tax_amount']
df_tax

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,0.000,0.000
1,1945945,2016-01-01,1,BABY CARE,0.000,0,0.000,0.000
2,1945946,2016-01-01,1,BEAUTY,0.000,0,0.000,0.000
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,0.000,0.000
4,1945948,2016-01-01,1,BOOKS,0.000,0,0.000,0.000
...,...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,21.907,460.040
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,7.728,162.281
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,120.986,2540.715
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,6.050,127.050
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,0.800,16.800

In [6]:
# Re-organizing the columns - Method 1
df1 = df_tax[['id', 'date', 'family', 'onpromotion', 'store_nbr', 'sales', 'tax_amount', 'total']]
df1.head(3)

,id,date,family,onpromotion,store_nbr,sales,tax_amount,total
0,1945944,2016-01-01,AUTOMOTIVE,0,1,0.0,0.0,0.0
1,1945945,2016-01-01,BABY CARE,0,1,0.0,0.0,0.0
2,1945946,2016-01-01,BEAUTY,0,1,0.0,0.0,0.0

In [7]:
df2 = df_tax.reindex(labels=['id', 'date', 'family', 'onpromotion', 'store_nbr', 'sales', 'tax_amount', 'total'], axis=1)
df2.head(3)

,id,date,family,onpromotion,store_nbr,sales,tax_amount,total
0,1945944,2016-01-01,AUTOMOTIVE,0,1,0.0,0.0,0.0
1,1945945,2016-01-01,BABY CARE,0,1,0.0,0.0,0.0
2,1945946,2016-01-01,BEAUTY,0,1,0.0,0.0,0.0

---

## Boolean Columns

In [8]:
df_tax['taxable_category'] = df_tax['family'] != 'BABY CARE'
df_tax.head()

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total,taxable_category
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,0.0,0.0,True
1,1945945,2016-01-01,1,BABY CARE,0.0,0,0.0,0.0,False
2,1945946,2016-01-01,1,BEAUTY,0.0,0,0.0,0.0,True
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,0.0,0.0,True
4,1945948,2016-01-01,1,BOOKS,0.0,0,0.0,0.0,True

In [11]:
# Calculating the taxes wheather a True condition
df['tax_amount'] = (
    df['sales']*0.05 * (df['family'] != 'BABY CARE')
)
df

,id,date,store_nbr,family,sales,onpromotion,tax_amount
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,0.00000
1,1945945,2016-01-01,1,BABY CARE,0.000,0,0.00000
2,1945946,2016-01-01,1,BEAUTY,0.000,0,0.00000
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,0.00000
4,1945948,2016-01-01,1,BOOKS,0.000,0,0.00000
...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,21.90665
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,7.72765
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,120.98645
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,6.05000
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,0.80000

---

In [18]:
oil = pd.read_csv('Data/oil.csv')
oil.columns = ['date', 'price']
oil['benchmark'] = 90

oil['date'] = pd.to_datetime(oil['date'])
oil['month'] = oil['date'].dt.month
oil.sort_values(by=['date', 'price'], ascending=[True, False], inplace=True)
oil

           date  price  benchmark  month
0    2013-01-01    NaN         90      1
1    2013-01-02  93.14         90      1
2    2013-01-03  92.97         90      1
3    2013-01-04  93.12         90      1
4    2013-01-07  93.20         90      1
...         ...    ...        ...    ...
1213 2017-08-25  47.65         90      8
1214 2017-08-28  46.40         90      8
1215 2017-08-29  46.46         90      8
1216 2017-08-30  45.96         90      8
1217 2017-08-31  47.26         90      8

[1218 rows x 4 columns]

In [19]:
oil['benchmark_ratio'] = oil.loc[:, 'price']/ oil.loc[:, 'benchmark']
oil

           date  price  benchmark  month  benchmark_ratio
0    2013-01-01    NaN         90      1              NaN
1    2013-01-02  93.14         90      1         1.034889
2    2013-01-03  92.97         90      1         1.033000
3    2013-01-04  93.12         90      1         1.034667
4    2013-01-07  93.20         90      1         1.035556
...         ...    ...        ...    ...              ...
1213 2017-08-25  47.65         90      8         0.529444
1214 2017-08-28  46.40         90      8         0.515556
1215 2017-08-29  46.46         90      8         0.516222
1216 2017-08-30  45.96         90      8         0.510667
1217 2017-08-31  47.26         90      8         0.525111

[1218 rows x 5 columns]

In [20]:
oil['buy'] = oil.loc[:, 'benchmark_ratio'] < 0.8
oil

           date  price  benchmark  month  benchmark_ratio    buy
0    2013-01-01    NaN         90      1              NaN  False
1    2013-01-02  93.14         90      1         1.034889  False
2    2013-01-03  92.97         90      1         1.033000  False
3    2013-01-04  93.12         90      1         1.034667  False
4    2013-01-07  93.20         90      1         1.035556  False
...         ...    ...        ...    ...              ...    ...
1213 2017-08-25  47.65         90      8         0.529444   True
1214 2017-08-28  46.40         90      8         0.515556   True
1215 2017-08-29  46.46         90      8         0.516222   True
1216 2017-08-30  45.96         90      8         0.510667   True
1217 2017-08-31  47.26         90      8         0.525111   True

[1218 rows x 6 columns]

---

# ASSIGNMENT: COLUMN CREATION

---

In [23]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.rename(columns={'store_nbr':'store_number',
                             'transactions':'transaction_count'}, 
                    inplace=True)
transactions.head(3)

         date  store_number  transaction_count
0  2013-01-01            25                770
1  2013-01-02             1               2111
2  2013-01-02             2               2358

In [33]:
transactions['pct_target'] = transactions['transaction_count']/2500
transactions['met_target'] = transactions['pct_target'].apply(lambda x: True if x >= 1 else False)
transactions['bonus_payable'] = transactions['met_target'].apply(lambda x: 100 if x == True else 0)

transactions['date'] = pd.to_datetime(transactions['date'])
transactions['month'] = transactions['date'].dt.month
transactions['day_of_week'] = transactions['date'].dt.dayofweek
transactions

,date,store_number,transaction_count,pct_target,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.3080,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1
83484,2017-08-15,51,1573,0.6292,False,0,8,1
83485,2017-08-15,52,2255,0.9020,False,0,8,1
83486,2017-08-15,53,932,0.3728,False,0,8,1
83487,2017-08-15,54,802,0.3208,False,0,8,1

In [32]:
print(f'Bonus Payable = {transactions['bonus_payable'].sum()}')

Bonus Payable = 1448300