---

# ADVANCED CONDITONAL COLUMNS WITH SELECT

---

>NumPy's `select()` function lets you create columns based on multiple conditions.
>* This is more flexible than `np.where()` function or `pd.where()` method

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df['tax_amount'] = df['sales'] * 0.05
df['total'] = df['sales'] + df['tax_amount']
df['taxable_category'] = df['family'] != 'BABY CARE'
df

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total,taxable_category
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,0.00000,0.00000,True
1,1945945,2016-01-01,1,BABY CARE,0.000,0,0.00000,0.00000,False
2,1945946,2016-01-01,1,BEAUTY,0.000,0,0.00000,0.00000,True
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,0.00000,0.00000,True
4,1945948,2016-01-01,1,BOOKS,0.000,0,0.00000,0.00000,True
...,...,...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,21.90665,460.03965,True
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,7.72765,162.28065,True
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,120.98645,2540.71545,True
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,6.05000,127.05000,True
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,0.80000,16.80000,True

In [3]:
conditions = [
    (df['date'] == '2017-02-23') & (df['family'] == 'BABY CARE'),
    (df['date'] == '2016-12-24') & (df['family'] == 'BOOKS'),
    (df['date'] == '2016-09-06') & (df['store_nbr'] > 28),
]

choices = ['Winter Clearance', 'Christmas Eve', 'New Store Special']

df['Sale_Name'] = np.select(condlist=conditions, choicelist=choices, default='No Sale')
df

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total,taxable_category,Sale_Name
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,0.00000,0.00000,True,No Sale
1,1945945,2016-01-01,1,BABY CARE,0.000,0,0.00000,0.00000,False,No Sale
2,1945946,2016-01-01,1,BEAUTY,0.000,0,0.00000,0.00000,True,No Sale
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,0.00000,0.00000,True,No Sale
4,1945948,2016-01-01,1,BOOKS,0.000,0,0.00000,0.00000,True,No Sale
...,...,...,...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,21.90665,460.03965,True,No Sale
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,7.72765,162.28065,True,No Sale
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,120.98645,2540.71545,True,No Sale
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,6.05000,127.05000,True,No Sale
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,0.80000,16.80000,True,No Sale

In [4]:
df['Sale_Name'].value_counts()

Sale_Name
No Sale              1053978
New Store Special        858
Christmas Eve             54
Winter Clearance          54
Name: count, dtype: int64

---

In [5]:
oil = pd.read_csv('Data/oil.csv')
oil.columns = ['date', 'price']
oil.head()

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [6]:
oil1 = oil.copy()
oil1['buy'] = np.where(oil1['price'] > 100, 'Too High', 'Buy')
oil1

            date  price  buy
0     2013-01-01    NaN  Buy
1     2013-01-02  93.14  Buy
2     2013-01-03  92.97  Buy
3     2013-01-04  93.12  Buy
4     2013-01-07  93.20  Buy
...          ...    ...  ...
1213  2017-08-25  47.65  Buy
1214  2017-08-28  46.40  Buy
1215  2017-08-29  46.46  Buy
1216  2017-08-30  45.96  Buy
1217  2017-08-31  47.26  Buy

[1218 rows x 3 columns]

In [7]:
oil1['buy'].value_counts()

buy
Buy         1036
Too High     182
Name: count, dtype: int64

---

In [8]:
conditions =[
    (oil.price > 100),
    (oil.price <= 100) & (oil.price > 50),
    (oil.price < 50)
]

choices = ["Don't Buy", "Buy", "Strong Buy"]

oil['buy'] = np.select(condlist=conditions, choicelist=choices, default='Missing')
oil.head()

         date  price      buy
0  2013-01-01    NaN  Missing
1  2013-01-02  93.14      Buy
2  2013-01-03  92.97      Buy
3  2013-01-04  93.12      Buy
4  2013-01-07  93.20      Buy

In [9]:
oil.tail()

            date  price         buy
1213  2017-08-25  47.65  Strong Buy
1214  2017-08-28  46.40  Strong Buy
1215  2017-08-29  46.46  Strong Buy
1216  2017-08-30  45.96  Strong Buy
1217  2017-08-31  47.26  Strong Buy

In [10]:
oil.buy.value_counts()

buy
Buy           512
Strong Buy    481
Don't Buy     182
Missing        43
Name: count, dtype: int64

---

# ASSIGNMENT: NUMPY SELECT

---

In [11]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [12]:
transactions['date'] = pd.to_datetime(transactions['date'])
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

---

Create a ‘seasonal_bonus’ column that applies to these dates:

    * All days in December: Call the December bonus `Holiday Bonus`
    * Sundays in May: Call the May bonus `Corporate Month`
    * Mondays in July: Call the August bonus ‘Summer Special’

If no bonus applies, the column should display `None`. Finally, calculate the total bonus owed at $100 per day.

---

In [13]:
# The Complete Week Index: Monday=0, Tuesday=1, Wednesday=2, Thursday=3, Friday=4, Saturday=5, Sunday=6
# thos numbers work for "dt.dayofweek" or "dt.day_of_week"

conditions = [
    (transactions['date'].dt.month == 12),
    (transactions['date'].dt.month == 5) & (transactions['date'].dt.dayofweek == 6),
    (transactions['date'].dt.month == 7) & (transactions['date'].dt.day_of_week == 0)
]

choices = ['Holiday Bonus', 'Corporate Month', 'Summer Special']

transactions['seasonal_bonus'] = np.select(condlist=conditions, choicelist=choices, default='None')
transactions.head()

        date  store_nbr  transactions seasonal_bonus
0 2013-01-01         25           770           None
1 2013-01-02          1          2111           None
2 2013-01-02          2          2358           None
3 2013-01-02          3          3487           None
4 2013-01-02          4          1922           None

In [14]:
transactions['seasonal_bonus'].value_counts()

seasonal_bonus
None               75259
Holiday Bonus       6028
Summer Special      1103
Corporate Month     1098
Name: count, dtype: int64

In [15]:
(transactions['seasonal_bonus'] != 'None').sum()*100

np.int64(822900)