---

<br>

# MULTI-INDEX DATAFRAMES

<br>

---

>`Multi-Index DataFrames` are generally created through aggregation operations. 
>   - They are stored as a list of tuples, with an item for each layer of the index.

In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [13]:
sales_sum = retail.groupby(['family', 'store_nbr'])[['sales']].sum().round(2)
sales_sum

                         sales
family     store_nbr
AUTOMOTIVE 1           2524.00
           2           3918.00
           3           6790.00
           4           2565.00
           5           3667.00
...                        ...
SEAFOOD    50         12773.97
           51         34250.95
           52          1219.48
           53          3745.18
           54          1082.00

[1782 rows x 1 columns]

In [14]:
sales_sum.index

MultiIndex([('AUTOMOTIVE',  1),
            ('AUTOMOTIVE',  2),
            ('AUTOMOTIVE',  3),
            ('AUTOMOTIVE',  4),
            ('AUTOMOTIVE',  5),
            ('AUTOMOTIVE',  6),
            ('AUTOMOTIVE',  7),
            ('AUTOMOTIVE',  8),
            ('AUTOMOTIVE',  9),
            ('AUTOMOTIVE', 10),
            ...
            (   'SEAFOOD', 45),
            (   'SEAFOOD', 46),
            (   'SEAFOOD', 47),
            (   'SEAFOOD', 48),
            (   'SEAFOOD', 49),
            (   'SEAFOOD', 50),
            (   'SEAFOOD', 51),
            (   'SEAFOOD', 52),
            (   'SEAFOOD', 53),
            (   'SEAFOOD', 54)],
           names=['family', 'store_nbr'], length=1782)

---

## 1. Accessing Rows via `outer index`

In [19]:
sales_sum.loc['AUTOMOTIVE'].head()

            sales
store_nbr
1          2524.0
2          3918.0
3          6790.0
4          2565.0
5          3667.0

In [20]:
sales_sum.loc['AUTOMOTIVE':'BEAUTY']

                       sales
family     store_nbr
AUTOMOTIVE 1          2524.0
           2          3918.0
           3          6790.0
           4          2565.0
           5          3667.0
...                      ...
BEAUTY     50         6353.0
           51         3566.0
           52          972.0
           53         3812.0
           54          405.0

[162 rows x 1 columns]

---

## 2. Accessing Rows via `Outer` & `Inner` Indices

In [24]:
# One value of the tuple
sales_sum.loc[('AUTOMOTIVE', 5), :]

sales    3667.0
Name: (AUTOMOTIVE, 5), dtype: float64

In [32]:
# A range of values from the tuple
sales_sum.loc[('AUTOMOTIVE', 48):('BEAUTY', 2), :]

                       sales
family     store_nbr
AUTOMOTIVE 48         7264.0
           49         7477.0
           50         6702.0
           51         4487.0
           52         1497.0
...                      ...
BABY CARE  52            0.0
           53           22.0
           54          198.0
BEAUTY     1          1776.0
           2          3824.0

[63 rows x 1 columns]

---

## LABORATORY

In [33]:
premier_league = pd.read_excel('Data/premier_league_games_full.xlsx')
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [36]:
premier_league.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3040 entries, 0 to 3039
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3040 non-null   int64
 1   league_name  3040 non-null   object
 2   season       3040 non-null   object
 3   HomeTeam     3040 non-null   object
 4   AwayTeam     3040 non-null   object
 5   HomeGoals    3040 non-null   int64
 6   AwayGoals    3040 non-null   int64
dtypes: int64(3), object(4)
memory usage: 166.4+ KB

In [34]:
agg_premier_league = premier_league.groupby(['season', 'HomeTeam'])[['HomeGoals']].sum()
agg_premier_league.head()

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21
          Chelsea                  33

In [41]:
# Selecting a single value - Method 1
agg_premier_league.loc['2008/2009', 'Arsenal']

HomeGoals    31
Name: (2008/2009, Arsenal), dtype: int64

In [42]:
# Selecting a single value - Method 2
agg_premier_league.loc[('2008/2009', 'Arsenal')]

HomeGoals    31
Name: (2008/2009, Arsenal), dtype: int64

In [45]:
# Selecting a range of values from a Multi-Index DF (Method 1)
agg_premier_league.loc['2008/2009':'2010/2011']

                                   HomeGoals
season    HomeTeam
2008/2009 Arsenal                         31
          Aston Villa                     27
          Blackburn Rovers                22
          Bolton Wanderers                21
          Chelsea                         33
          Everton                         31
          Fulham                          28
          Hull City                       18
          Liverpool                       41
          Manchester City                 40
          Manchester United               43
          Middlesbrough                   17
          Newcastle United                24
          Portsmouth                      26
          Stoke City                      22
          Sunderland                      21
          Tottenham Hotspur               21
          West Bromwich Albion            26
          West Ham United                 23
          Wigan Athletic                  17
2009/2010 Arsenal                         48
          Aston Villa                     29
          Birmingham City                 19
          Blackburn Rovers                28
          Bolton Wanderers                26
          Burnley                         25
          Chelsea                         68
          Everton                         35
          Fulham                          27
          Hull City                       22
          Liverpool                       43
          Manchester City                 41
          Manchester United               52
          Portsmouth                      24
          Stoke City                      24
          Sunderland                      32
          Tottenham Hotspur               40
          West Ham United                 30
          Wigan Athletic                  19
          Wolverhampton Wanderers         13
2010/2011 Arsenal                         33
          Aston Villa                     26
          Birmingham City                 19
          Blackburn Rovers                22
          Blackpool                       30
          Bolton Wanderers                34
          Chelsea                         39
          Everton                         31
          Fulham                          30
          Liverpool                       37
          Manchester City                 34
          Manchester United               49
          Newcastle United                41
          Stoke City                      31
          Sunderland                      25
          Tottenham Hotspur               30
          West Bromwich Albion            30
          West Ham United                 24
          Wigan Athletic                  22
          Wolverhampton Wanderers         30

In [48]:
# Selecting a ranges of values from a Multi-Index DF (Method 2)
agg_premier_league.loc[('2008/2009', 'Arsenal'):('2008/2009', 'Chelsea')]

                            HomeGoals
season    HomeTeam
2008/2009 Arsenal                  31
          Aston Villa              27
          Blackburn Rovers         22
          Bolton Wanderers         21
          Chelsea                  33

In [51]:
# Selecting a range of values from a Multi-Index DF (Methos 3 - .iloc[])
agg_premier_league.iloc[3:7]

                            HomeGoals
season    HomeTeam
2008/2009 Bolton Wanderers         21
          Chelsea                  33
          Everton                  31
          Fulham                   28

---

## Aggregations with Multiple Calculations

In [54]:
agg_league = premier_league.groupby(['season', 'HomeTeam']).agg({'HomeGoals':['sum', 'mean', 'min', 'max']})
agg_league

                               HomeGoals
                                     sum      mean min max
season    HomeTeam
2008/2009 Arsenal                     31  1.631579   0   4
          Aston Villa                 27  1.421053   0   4
          Blackburn Rovers            22  1.157895   0   3
          Bolton Wanderers            21  1.105263   0   4
          Chelsea                     33  1.736842   0   5
...                                  ...       ...  ..  ..
2015/2016 Swansea City                20  1.052632   0   3
          Tottenham Hotspur           35  1.842105   0   4
          Watford                     20  1.052632   0   3
          West Bromwich Albion        20  1.052632   0   3
          West Ham United             34  1.789474   0   3

[160 rows x 4 columns]

In [57]:
# access values with '.iloc[]'
agg_league.iloc[1,3]

np.int64(4)

In [61]:
agg_league.loc[('2008/2009', 'Arsenal'), ('HomeGoals', 'max')]

np.int64(4)

---

In [60]:
agg_league.iloc[3,1]

np.float64(1.105263157894737)

In [62]:
agg_league.loc[('2008/2009', 'Bolton Wanderers'), ('HomeGoals', 'mean')]

np.float64(1.105263157894737)

---

In [55]:
agg_league.columns

MultiIndex([('HomeGoals',  'sum'),
            ('HomeGoals', 'mean'),
            ('HomeGoals',  'min'),
            ('HomeGoals',  'max')],
           )

In [56]:
agg_league.index

MultiIndex([('2008/2009',              'Arsenal'),
            ('2008/2009',          'Aston Villa'),
            ('2008/2009',     'Blackburn Rovers'),
            ('2008/2009',     'Bolton Wanderers'),
            ('2008/2009',              'Chelsea'),
            ('2008/2009',              'Everton'),
            ('2008/2009',               'Fulham'),
            ('2008/2009',            'Hull City'),
            ('2008/2009',            'Liverpool'),
            ('2008/2009',      'Manchester City'),
            ...
            ('2015/2016',     'Newcastle United'),
            ('2015/2016',         'Norwich City'),
            ('2015/2016',          'Southampton'),
            ('2015/2016',           'Stoke City'),
            ('2015/2016',           'Sunderland'),
            ('2015/2016',         'Swansea City'),
            ('2015/2016',    'Tottenham Hotspur'),
            ('2015/2016',              'Watford'),
            ('2015/2016', 'West Bromwich Albion'),
            ('2015/2016',      'West Ham United')],
           names=['season', 'HomeTeam'], length=160)

In [63]:
agg_league.loc['2008/2009', ('HomeGoals', 'mean')]

HomeTeam
Arsenal                 1.631579
Aston Villa             1.421053
Blackburn Rovers        1.157895
Bolton Wanderers        1.105263
Chelsea                 1.736842
Everton                 1.631579
Fulham                  1.473684
Hull City               0.947368
Liverpool               2.157895
Manchester City         2.105263
Manchester United       2.263158
Middlesbrough           0.894737
Newcastle United        1.263158
Portsmouth              1.368421
Stoke City              1.157895
Sunderland              1.105263
Tottenham Hotspur       1.105263
West Bromwich Albion    1.368421
West Ham United         1.210526
Wigan Athletic          0.894737
Name: (HomeGoals, mean), dtype: float64