---

# THE `.agg()` METHOD & NAMED AGGREGATIONS

---

>The `.agg()` method lets you perform multiple aggregations on a `groupby` object

In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

---

## 1. Single Calculation with `.agg()` Method

In [3]:
single_calc = retail.groupby(by=['store_nbr', 'family'])[['sales', 'onpromotion']].agg('sum').round()
single_calc

                                          sales  onpromotion
store_nbr family
1         AUTOMOTIVE                     2524.0           14
          BABY CARE                         0.0            0
          BEAUTY                         1776.0          190
          BEVERAGES                   1238601.0        13793
          BOOKS                           211.0            0
...                                         ...          ...
54        POULTRY                       35537.0          909
          PREPARED FOODS                42792.0          577
          PRODUCE                      378612.0         6734
          SCHOOL AND OFFICE SUPPLIES      997.0          277
          SEAFOOD                        1082.0          125

[1782 rows x 2 columns]

---

## 2. Multiple Calculation with `.agg()` Method

In [4]:
multiple_calc = retail.groupby(['store_nbr', 'family'])[['sales', 'onpromotion']].agg(['sum', 'mean']).round()
multiple_calc

                                          sales         onpromotion
                                            sum    mean         sum  mean
store_nbr family
1         AUTOMOTIVE                     2524.0     4.0          14   0.0
          BABY CARE                         0.0     0.0           0   0.0
          BEAUTY                         1776.0     3.0         190   0.0
          BEVERAGES                   1238601.0  2092.0       13793  23.0
          BOOKS                           211.0     0.0           0   0.0
...                                         ...     ...         ...   ...
54        POULTRY                       35537.0    60.0         909   2.0
          PREPARED FOODS                42792.0    72.0         577   1.0
          PRODUCE                      378612.0   640.0        6734  11.0
          SCHOOL AND OFFICE SUPPLIES      997.0     2.0         277   0.0
          SEAFOOD                        1082.0     2.0         125   0.0

[1782 rows x 4 columns]

---

## 3. Specific Aggregations by Column

In [5]:
spec_agg = (retail
    .groupby(['store_nbr', 'family'])
    .agg({'sales':['sum','mean', 'std'],
          'onpromotion':['min', 'mean', 'max']})
    .round())

spec_agg

                                          sales                onpromotion  \
                                            sum    mean    std         min
store_nbr family
1         AUTOMOTIVE                     2524.0     4.0    3.0           0
          BABY CARE                         0.0     0.0    0.0           0
          BEAUTY                         1776.0     3.0    2.0           0
          BEVERAGES                   1238601.0  2092.0  605.0           0
          BOOKS                           211.0     0.0    1.0           0
...                                         ...     ...    ...         ...
54        POULTRY                       35537.0    60.0   24.0           0
          PREPARED FOODS                42792.0    72.0   26.0           0
          PRODUCE                      378612.0   640.0  175.0           0
          SCHOOL AND OFFICE SUPPLIES      997.0     2.0    5.0           0
          SEAFOOD                        1082.0     2.0    2.0           0


                                      mean max
store_nbr family
1         AUTOMOTIVE                   0.0   1
          BABY CARE                    0.0   0
          BEAUTY                       0.0   2
          BEVERAGES                   23.0  84
          BOOKS                        0.0   0
...                                    ...  ..
54        POULTRY                      2.0  11
          PREPARED FOODS               1.0   7
          PRODUCE                     11.0  83
          SCHOOL AND OFFICE SUPPLIES   0.0   8
          SEAFOOD                      0.0   2

[1782 rows x 6 columns]

---

## 4. Name Aggregated Columns

In [6]:
name_agg = (retail
    .groupby(['store_nbr', 'family'])
    .agg(sales_sum=('sales', 'sum'),
         sales_avg=('sales', 'mean'),
         sales_std=('sales', 'std'),
         on_promotion_max=('onpromotion', 'max'),
         on_promotion_mean=('onpromotion', 'mean'))
).round()
name_agg

                                      sales_sum  sales_avg  sales_std  \
store_nbr family
1         AUTOMOTIVE                     2524.0        4.0        3.0
          BABY CARE                         0.0        0.0        0.0
          BEAUTY                         1776.0        3.0        2.0
          BEVERAGES                   1238601.0     2092.0      605.0
          BOOKS                           211.0        0.0        1.0
...                                         ...        ...        ...
54        POULTRY                       35537.0       60.0       24.0
          PREPARED FOODS                42792.0       72.0       26.0
          PRODUCE                      378612.0      640.0      175.0
          SCHOOL AND OFFICE SUPPLIES      997.0        2.0        5.0
          SEAFOOD                        1082.0        2.0        2.0

                                      on_promotion_max  on_promotion_mean
store_nbr family
1         AUTOMOTIVE                                 1                0.0
          BABY CARE                                  0                0.0
          BEAUTY                                     2                0.0
          BEVERAGES                                 84               23.0
          BOOKS                                      0                0.0
...                                                ...                ...
54        POULTRY                                   11                2.0
          PREPARED FOODS                             7                1.0
          PRODUCE                                   83               11.0
          SCHOOL AND OFFICE SUPPLIES                 8                0.0
          SEAFOOD                                    2                0.0

[1782 rows x 5 columns]

---

## LABORATORY

In [7]:
premier_league = pd.read_excel('Data/premier_league_games_full.xlsx')
premier_league.head(3)

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1

In [8]:
premier_grouped = (premier_league
    .groupby(['season', 'HomeTeam'], as_index=False)
    .agg({'HomeGoals':['sum', 'mean'],
          'AwayGoals':['sum', 'mean']})
)
premier_grouped

        season              HomeTeam HomeGoals           AwayGoals
                                           sum      mean       sum      mean
0    2008/2009               Arsenal        31  1.631579        16  0.842105
1    2008/2009           Aston Villa        27  1.421053        21  1.105263
2    2008/2009      Blackburn Rovers        22  1.157895        23  1.210526
3    2008/2009      Bolton Wanderers        21  1.105263        21  1.105263
4    2008/2009               Chelsea        33  1.736842        12  0.631579
..         ...                   ...       ...       ...       ...       ...
155  2015/2016          Swansea City        20  1.052632        20  1.052632
156  2015/2016     Tottenham Hotspur        35  1.842105        15  0.789474
157  2015/2016               Watford        20  1.052632        19  1.000000
158  2015/2016  West Bromwich Albion        20  1.052632        26  1.368421
159  2015/2016       West Ham United        34  1.789474        26  1.368421

[160 rows x 6 columns]

In [9]:
name_grouped = (premier_league
    .groupby(['season', 'HomeTeam'], as_index=False)
    .agg(
        homegoal_mean=('HomeGoals', 'mean'),
        homegoal_sum=('HomeGoals', 'sum'),
        AwayGoal_mean=('AwayGoals', 'mean'),
        AwayGoal_sum=('AwayGoals', 'sum')
    ).round()
)
name_grouped

,season,HomeTeam,homegoal_mean,homegoal_sum,AwayGoal_mean,AwayGoal_sum
0,2008/2009,Arsenal,2.0,31,1.0,16
1,2008/2009,Aston Villa,1.0,27,1.0,21
2,2008/2009,Blackburn Rovers,1.0,22,1.0,23
3,2008/2009,Bolton Wanderers,1.0,21,1.0,21
4,2008/2009,Chelsea,2.0,33,1.0,12
...,...,...,...,...,...,...
155,2015/2016,Swansea City,1.0,20,1.0,20
156,2015/2016,Tottenham Hotspur,2.0,35,1.0,15
157,2015/2016,Watford,1.0,20,1.0,19
158,2015/2016,West Bromwich Albion,1.0,20,1.0,26
159,2015/2016,West Ham United,2.0,34,1.0,26

<br><br>

---

## ASSIGNMENT: THE AGG METHOD

In [10]:
transactions = pd.read_csv('Data/transactions.csv', parse_dates=['date'])

transactions = transactions.assign(
    target_pct = transactions.transactions / 2500,
    met_target = transactions.transactions / 2500 >= 1,
    bonus_payable = (transactions.transactions / 2500 >= 1) * 100,
    month = transactions.date.dt.month,
    day_of_week = transactions.date.dt.day_of_week
)

transactions.head()

,date,store_nbr,transactions,target_pct,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.3080,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2

### 1. By Store

In [11]:
(transactions
    .groupby('store_nbr')
    .agg({'met_target':'mean', 'bonus_payable':'sum'})
    .sort_values(by='bonus_payable', ascending=False)
).head()

           met_target  bonus_payable
store_nbr
47           0.999404         167600
44           0.998807         167500
3            0.998210         167300
45           0.997615         167300
46           0.989267         165900

### 2. By Month

In [12]:
(transactions
 .groupby('month')
 .agg({'met_target':'mean', 'bonus_payable':'sum'})
 .sort_values(by='bonus_payable', ascending=False)    
).head()

       met_target  bonus_payable
month
12       0.255640         154100
5        0.170792         131800
3        0.169461         130400
4        0.174469         129700
7        0.162486         126300

### 3. By Weekday

In [13]:
(transactions
    .groupby('day_of_week')
    .agg({'met_target':'mean', 'bonus_payable':'sum'})
    .sort_values(by='bonus_payable', ascending=False)
).head()

             met_target  bonus_payable
day_of_week
5              0.222204         266400
6              0.204001         241700
4              0.179007         213000
0              0.160214         191600
2              0.160572         191000