---

# TEXT SERIES OPERATIONS

---

>The Pandas `str` accessor lets you access many string methods
>  - These methods all return a Series (split returns multiple series)

<br>

>|**STRING METHOD**|**DESCRIPTION**|
>|:---|:---|
>|**.strip(), .lstrip(), .rstrip()**|Removes all leading and/or trailing characters (spaces by default)|
>|**.upper(), .lower()**|Converts all characters to upper or lower case|
>|**.slice(start:stop:step)**|Applies a slice to the strings in a Series|
>|**.count("string")**|Counts all instances of a given string|
>|**.contains("string")**|Returns `True` if a given string is found; `False` if not|
>|**.replace("a", "b")**|Replaces instances of string "a" with string "b"|
>|**.split("delimiter", expand=True)**|Splits strings based on a given delimiter string, and returns a DataFrame with a Series for each split|
>|**.len()**|Returns the length of each string in a Series|
>|**.startswith("string", .endswith("string")**)|Returns `True` if a string starts or ends with given string; `False` if not|

<br>

In [1]:
import numpy as np
import pandas as pd

In [ ]:
prices = pd.Series(data=["$3.99", "$5.99", "$22.99", "$7.99", "$33.99"])
prices

0     $3.99
1     $5.99
2    $22.99
3     $7.99
4    $33.99
dtype: object

In [ ]:
# Look for the string '3'
prices.str.contains("3")

0     True
1    False
2    False
3    False
4     True
dtype: bool

In [ ]:
# Remove '$' and convert numbers into floats
clean = prices.str.strip("$").astype("float")
print(f"Shape of the data: {clean.shape}\n")
clean

Shape of the data: (5,)

0     3.99
1     5.99
2    22.99
3     7.99
4    33.99
dtype: float64

In [ ]:
string_series = pd.Series(data=["day 0", "day 1", "day 2", "day 3", "day 4"])
string_series

0    day 0
1    day 1
2    day 2
3    day 3
4    day 4
dtype: object

In [ ]:
# using 'contains' methods
string_series.str.contains("1")

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [ ]:
# Using 2 Methods on a single line of code
string_series.str.upper().str.contains("A")

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [ ]:
# Cleaning 'day ' from each row and converting into int (METHOD 1)
string_series.str.strip("day ").astype("int")

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
# Cleaning 'day ' from each row and converting into int  (METHOD 2)
string_series.str.slice(-1).astype("int")

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
# Cleaning 'day ' from each row and converting into int  (METHOD 3)
string_series.str[-1].astype("int")

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
# Slicing - Method 1
string_series.str.slice(1, 3)

0    ay
1    ay
2    ay
3    ay
4    ay
dtype: object

In [ ]:
# Slicing - Method 2
string_series.str[1:3]

0    ay
1    ay
2    ay
3    ay
4    ay
dtype: object

In [ ]:
# Splitting with 'expand=False' - It is a Series
string_series.str.split(" ", expand=False)

0    [day, 0]
1    [day, 1]
2    [day, 2]
3    [day, 3]
4    [day, 4]
dtype: object

In [ ]:
# Splitting with 'expand=True' - It is a DataFrame
string_series.str.split(" ", expand=True)

     0  1
0  day  0
1  day  1
2  day  2
3  day  3
4  day  4

In [ ]:
# Provided series with combined age and label data
age_data = pd.Series(["Adult 25", "Child 12", "Adult 64", "Teen 17", "Adult 45"])

# Split the string to separate the age from the labels
split_data = age_data.str.split(" ", expand=True)
split_data

       0   1
0  Adult  25
1  Child  12
2  Adult  64
3   Teen  17
4  Adult  45

In [ ]:
split_data[1] = split_data[1].astype("int")
split_data

       0   1
0  Adult  25
1  Child  12
2  Adult  64
3   Teen  17
4  Adult  45

---

# ASSIGNMENT: SERIES OPERATIONS

---

* Increase the prices in the oil series by 10%, and add an additional 2 dollars per barrel on top of that.

* Then, create a series that represents the difference between each price and max price.

* Finally, extract the month from the string dates in the index and store them as an integer in their own series.

In [ ]:
oil = pd.read_csv("Data/oil.csv", index_col="date").dropna()

print(f"  - Data Shape: {oil.shape}\n  - Data Type: {type(oil)}\n")
oil.head()

  - Data Shape: (1175, 1)
  - Data Type: <class 'pandas.core.frame.DataFrame'>

            dcoilwtico
date
2013-01-02       93.14
2013-01-03       92.97
2013-01-04       93.12
2013-01-07       93.20
2013-01-08       93.21

In [ ]:
oil = oil["dcoilwtico"].rename(index="price")

print(f"  - Data Shape: {oil.shape}\n  - Data Type: {type(oil)}\n")
oil.head()

  - Data Shape: (1175,)
  - Data Type: <class 'pandas.core.series.Series'>

date
2013-01-02    93.14
2013-01-03    92.97
2013-01-04    93.12
2013-01-07    93.20
2013-01-08    93.21
Name: price, dtype: float64

In [38]:
oil = oil[1000:1100]
oil

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: price, Length: 100, dtype: float64

In [ ]:
# Increase the prices in the oil series by 10%, and add an additional 2 dollars per barrel on top of that.
oil_percent = round(oil.mul(1.1), 3).add(2)
oil_percent

date
2016-12-20    59.442
2016-12-21    58.584
2016-12-22    59.178
2016-12-23    59.211
2016-12-27    60.102
               ...
2017-05-09    52.424
2017-05-10    54.008
2017-05-11    54.591
2017-05-12    54.613
2017-05-15    55.746
Name: price, Length: 100, dtype: float64

In [ ]:
# Then, create a series that represents the difference between each price and max price.
max_price = oil.max()
print(max_price, "\n")
oil_diff = oil.sub(max_price).div(max_price).round(4)
oil_diff

54.48

date
2016-12-20   -0.0415
2016-12-21   -0.0558
2016-12-22   -0.0459
2016-12-23   -0.0453
2016-12-27   -0.0305
               ...
2017-05-09   -0.1586
2017-05-10   -0.1322
2017-05-11   -0.1224
2017-05-12   -0.1221
2017-05-15   -0.1032
Name: price, Length: 100, dtype: float64

In [ ]:
# Finally, extract the month from the string dates in the index and store them as an integer in their own series.
month = oil.index.str[5:7].astype("int")
print(month, "\n\n")

month_series = pd.Series(data=month)
month_series

Index([12, 12, 12, 12, 12, 12, 12, 12,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
      dtype='int64', name='date')

0     12
1     12
2     12
3     12
4     12
      ..
95     5
96     5
97     5
98     5
99     5
Name: date, Length: 100, dtype: int64